### ISSUE TITLE
server trows internal server error if user registers with ssl with email registered before

### ISSUE THREAD

**Issue by Claymanus** [edemo/PDOauth#151]
Jun 15 21:29:18 drezina apache2[29385]: [:error] [pid 29385] ERROR:pdoauth.app:Exception on /keygen [POST]
Jun 15 21:29:18 drezina apache2[29385]: [:error] [pid 29385] Traceback (most recent call last):
Jun 15 21:29:18 drezina apache2[29385]: [:error] [pid 29385]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
Jun 15 21:29:18 drezina apache2[29385]: [:error] [pid 29385]     response = self.full_dispatch_request()
Jun 15 21:29:18 drezina apache2[29385]: [:error] [pid 29385]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
Jun 15 21:29:18 drezina apache2[29385]: [:error] [pid 29385]     rv = self.handle_user_exception(e)
Jun 15 21:29:18 drezina apache2[29385]: [:error] [pid 29385]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
Jun 15 21:29:18 drezina apache2[29385]: [:error] [pid 29385]     reraise(exc_type, exc_value, tb)
Jun 15 21:29:18 drezina apache2[29385]: [:error] [pid 29385]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
Jun 15 21:29:18 drezina apache2[29385]: [:error] [pid 29385]     rv = self.dispatch_request()
Jun 15 21:29:18 drezina apache2[29385]: [:error] [pid 29385]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
Jun 15 21:29:18 drezina apache2[29385]: [:error] [pid 29385]     return self.view_functions[rule.endpoint](**req.view_args)
Jun 15 21:29:18 drezina apache2[29385]: [:error] [pid 29385]   File "/usr/local/PDOauth/src/pdoauth/Decorators.py", line 34, in validated
Jun 15 21:29:18 drezina apache2[29385]: [:error] [pid 29385]     return self.runInterfaceFunc(func, args, kwargs, formClass, status, checkLoginFunction)
Jun 15 21:29:18 drezina apache2[29385]: [:error] [pid 29385]   File "/usr/local/PDOauth/src/pdoauth/Decorators.py", line 20, in runInterfaceFunc
Jun 15 21:29:18 drezina apache2[29385]: [:error] [pid 29385]     return func(*args, **kwargs)
Jun 15 21:29:18 drezina apache2[29385]: [:error] [pid 29385]   File "/usr/local/PDOauth/src/pdoauth/main.py", line 60, in keygen
Jun 15 21:29:18 drezina apache2[29385]: [:error] [pid 29385]     return controller.do_keygen(form)
Jun 15 21:29:18 drezina apache2[29385]: [:error] [pid 29385]   File "/usr/local/PDOauth/src/pdoauth/CertificateHandling.py", line 37, in do_keygen
Jun 15 21:29:18 drezina apache2[29385]: [:error] [pid 29385]     self.registerAndLoginCertUser(email, certAsPem)
Jun 15 21:29:18 drezina apache2[29385]: [:error] [pid 29385]   File "/usr/local/PDOauth/src/pdoauth/CertificateHandling.py", line 13, in registerAndLoginCertUser
Jun 15 21:29:18 drezina apache2[29385]: [:error] [pid 29385]     cred = self.registerCertUser(cert, [email])
Jun 15 21:29:18 drezina apache2[29385]: [:error] [pid 29385]   File "/usr/local/PDOauth/src/pdoauth/CertificateHandling.py", line 54, in registerCertUser
Jun 15 21:29:18 drezina apache2[29385]: [:error] [pid 29385]     CredentialManager.create_user_with_creds("certificate", identifier, digest, theEmail)
Jun 15 21:29:18 drezina apache2[29385]: [:error] [pid 29385]   File "/usr/local/PDOauth/src/pdoauth/CredentialManager.py", line 13, in create_user_with_creds
Jun 15 21:29:18 drezina apache2[29385]: [:error] [pid 29385]     user = User.new(email, digest)
Jun 15 21:29:18 drezina apache2[29385]: [:error] [pid 29385]   File "/usr/local/PDOauth/src/pdoauth/models/User.py", line 30, in new
Jun 15 21:29:18 drezina apache2[29385]: [:error] [pid 29385]     raise AlreadyExistingUser()
Jun 15 21:29:18 drezina apache2[29385]: [:error] [pid 29385] AlreadyExistingUser
Jun 15 21:29:18 drezina apache[20490]: 127.0.1.1:443 192.168.8.10 - - [15/Jun/2015:21:29:18 +0200] "POST /keygen HTTP/1.1" 500 664 "https://local.sso.edemokraciagep.org/static/login.html" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.124 Safari/537.36"

**Comment by Claymanus** [comment]
szerintem ez megjavult
